### ISSUE TITLE
KeyError subscribers_count

### ISSUE THREAD

**Issue by noony** [infinityworksltd/github-exporter#16]
Hi,

it seems that this [PR](https://github.com/infinityworksltd/github-exporter/pull/14) introduced a bug cf the trace below it's maybe not always returned.

```
2017-5-2 18:11:59Traceback (most recent call last):
2017-5-2 18:11:59  File "github_exporter.py", line 131, in <module>
2017-5-2 18:11:59    REGISTRY.register(GitHubCollector())
2017-5-2 18:11:59  File "/usr/local/lib/python3.5/site-packages/prometheus_client/core.py", line 50, in register
2017-5-2 18:11:59    names = self._get_names(collector)
2017-5-2 18:11:59  File "/usr/local/lib/python3.5/site-packages/prometheus_client/core.py", line 86, in _get_names
2017-5-2 18:11:59    for metric in desc_func():
2017-5-2 18:11:59  File "github_exporter.py", line 43, in collect
2017-5-2 18:11:59    self._collect_org_metrics(gauges, metrics)
2017-5-2 18:11:59  File "github_exporter.py", line 59, in _collect_org_metrics
2017-5-2 18:11:59    self._add_metrics(gauges, metrics, repo)
2017-5-2 18:11:59  File "github_exporter.py", line 119, in _add_metrics
2017-5-2 18:11:59    gauges[metric].add_metric([response_json['name'], response_json['owner']['login'], str(response_json['private']).lower()], value=response_json[field])
2017-5-2 18:11:59KeyError: 'subscribers_count'```

**Comment by Rucknar** [comment]
Thanks for the heads up @noony I've got a new version that's likely to be available for testing in the next few days.

**Comment by noony** [comment]
Hi, I can confirm that the exporter is working with the new version. Thanks ! 👍
